# padding is important
version: "3"   
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
    # bind mounting - project root directort: container folder
      - ./:/app
    # anoymous volume - ignore node_modules folder
      - /app/node_modules  
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env another option to add environment variable file
